### ISSUE TITLE
Where's the code?

### ISSUE THREAD

**Issue by JoeNemo** [gdavis-github/antlr4cl#1]
Hi, I don't see an implementation, was a LISP target ever done?

**Comment by gdavis-github** [comment]
Sorry ... I should have deleted this repo.

This project became defunct when I discovered Clojure. https://clojure.org/

**Comment by JoeNemo** [comment]
Thanks for actually responding!!  Maybe if I have to much coffee some day I will try to turn the javascript runtime for ANTLR into some lisp code.   The execution semantics of JS and Lisp are close enough that it should not require too much deep thought.
